// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3lnM7R99ayGKaPxhbrC-dDnnmZ2BURKA',
    appId: '1:428204339598:web:8a04b4376c6319a91eb4df',
    messagingSenderId: '428204339598',
    projectId: 'flutterapp-86da7',
    authDomain: 'flutterapp-86da7.firebaseapp.com',
    storageBucket: 'flutterapp-86da7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2daZ1dSe05do_1qpap4A2Bh3eL50KeJU',
    appId: '1:428204339598:android:be62dfa8b0c5a4481eb4df',
    messagingSenderId: '428204339598',
    projectId: 'flutterapp-86da7',
    storageBucket: 'flutterapp-86da7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYQ0NpSDeSVXDjc9PAY-cpePX8UBpLKic',
    appId: '1:428204339598:ios:73ce43c01b18470f1eb4df',
    messagingSenderId: '428204339598',
    projectId: 'flutterapp-86da7',
    storageBucket: 'flutterapp-86da7.appspot.com',
    iosClientId: '428204339598-u480cufl02eg02t0mbcb7skmi03jm02u.apps.googleusercontent.com',
    iosBundleId: 'com.example.fittrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYQ0NpSDeSVXDjc9PAY-cpePX8UBpLKic',
    appId: '1:428204339598:ios:73ce43c01b18470f1eb4df',
    messagingSenderId: '428204339598',
    projectId: 'flutterapp-86da7',
    storageBucket: 'flutterapp-86da7.appspot.com',
    iosClientId: '428204339598-u480cufl02eg02t0mbcb7skmi03jm02u.apps.googleusercontent.com',
    iosBundleId: 'com.example.fittrack',
  );
}
